build:
  tags: [ linux ]
  script:
    - export VERSION=`greycat build-version`
    - echo "${VERSION}"
    - ./gradlew -Pversion=${VERSION} buildPlugin
    - ./publish.sh
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - gradle
      - .gradle
  artifacts:
    expire_in: 1 month
    paths:
      - build/distributions/*.zip